import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";

const lato = Lato({ weight: ["400", "700", "900"],subsets:["latin"] });

export const metadata: Metadata = {
  title: "XandZap Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}

